version: '3.8'
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - EMAIL_COMPANY=${EMAIL_COMPANY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongo
      - redis
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: react-app
    restart: always
    ports:
      - '8888:80'
    environment:
      - REACT_APP_GRAPHQL_URI=http://app:3000/graphql
    networks:
      - backend

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

